spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: file://C:/Users/syeda/Downloads/MICROSERVICES-V2/config-repo

server:
  port: 8888
